# Author: Tanmay Rajore,Neha Jawalkar
#
# Copyright:
#     Copyright (c) 2024 Microsoft Research
#     Permission is hereby granted, free of charge, to any person obtaining a copy
#     of this software and associated documentation files (the "Software"), to deal
#     in the Software without restriction, including without limitation the rights
#     to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#     copies of the Software, and to permit persons to whom the Software is
#     furnished to do so, subject to the following conditions:
#     The above copyright notice and this permission notice shall be included in all
#     copies or substantial portions of the Software.
#     THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#     IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#     FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#     AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#     LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#     OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#     SOFTWARE.
FROM nvidia/cuda:11.8.0-devel-ubuntu22.04

WORKDIR /home
RUN ln -sf /bin/bash /bin/sh

RUN apt update && apt upgrade -y &&  apt install -y git apt-utils; \
    apt install -y sudo ; \
    sudo apt install -y gcc-9 g++-9; \
    sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9;\
    sudo update-alternatives --config gcc;\
    sudo apt install libssl-dev cmake python3-pip libgmp-dev libmpfr-dev -y;\
    sudo apt install cmake make libeigen3-dev -y ;

RUN git config --global --add safe.directory *
#RUN git submodule update --init --recursive
