/*
This is an autogenerated file, generated using the EzPC compiler.
*/

#include "emp-sh2pc/emp-sh2pc.h" 
using namespace emp;
using namespace std;
int bitlen = 32;
int party,port;
char *ip = "127.0.0.1"; 
template<typename T> 
vector<T> make_vector(size_t size) { 
return std::vector<T>(size); 
} 

template <typename T, typename... Args> 
auto make_vector(size_t first, Args... sizes) 
{ 
auto inner = make_vector<T>(sizes...); 
return vector<decltype(inner)>(first, inner); 
} 


int main(int argc, char** argv) {
parse_party_and_port(argv, &party, &port);
if(argc>3){
  ip=argv[3];
}
cout<<"Ip Address: "<<ip<<endl;
cout<<"Port: "<<port<<endl;
cout<<"Party: "<<(party==1? "CLIENT" : "SERVER")<<endl;
NetIO * io = new NetIO(party==ALICE ? nullptr : ip, port);
setup_semi_honest(io, party);


Integer x;
if ((party == BOB)) {
cout << ("Input x:") << endl;
}
/* Variable to read the clear value corresponding to the input variable x at (2,2-2,28) */
uint32_t __tmp_in_x;
if ((party == BOB)) {
cin >> __tmp_in_x;
}
x = Integer(bitlen, __tmp_in_x, BOB);

Bit b = x.operator<(Integer(bitlen,  (int32_t)3, PUBLIC));
cout << ("Value of b:") << endl;
cout << (b.reveal<bool>(PUBLIC)) << endl;


finalize_semi_honest();
delete io; 
 
return 0;
}

