/*
This is an autogenerated file, generated using the EzPC compiler.
*/

#include "emp-sh2pc/emp-sh2pc.h" 
using namespace emp;
using namespace std;
int bitlen = 64;
int party,port;
char *ip = "127.0.0.1"; 
template<typename T> 
vector<T> make_vector(size_t size) { 
return std::vector<T>(size); 
} 

template <typename T, typename... Args> 
auto make_vector(size_t first, Args... sizes) 
{ 
auto inner = make_vector<T>(sizes...); 
return vector<decltype(inner)>(first, inner); 
} 


int main(int argc, char** argv) {
parse_party_and_port(argv, &party, &port);
if(argc>3){
  ip=argv[3];
}
cout<<"Ip Address: "<<ip<<endl;
cout<<"Port: "<<port<<endl;
cout<<"Party: "<<(party==1? "CLIENT" : "SERVER")<<endl;
NetIO * io = new NetIO(party==ALICE ? nullptr : ip, port);
setup_semi_honest(io, party);


auto x = make_vector<Integer>( (int32_t)2,  (int32_t)3);
if ((party == BOB)) {
cout << ("Input x:") << endl;
}
/* Variable to read the clear value corresponding to the input variable x at (2,2-2,35) */
uint64_t __tmp_in_x;
for (uint32_t i0 =  (uint32_t)0; i0 <  (int32_t)2; i0++){
for (uint32_t i1 =  (uint32_t)0; i1 <  (int32_t)3; i1++){
if ((party == BOB)) {
cin >> __tmp_in_x;
}
x[i0][i1] = Integer(bitlen, __tmp_in_x, BOB);
}
}

auto y = make_vector<Integer>( (int32_t)2,  (int32_t)3);
if ((party == ALICE)) {
cout << ("Input y:") << endl;
}
/* Variable to read the clear value corresponding to the input variable y at (3,2-3,35) */
uint64_t __tmp_in_y;
for (uint32_t i0 =  (uint32_t)0; i0 <  (int32_t)2; i0++){
for (uint32_t i1 =  (uint32_t)0; i1 <  (int32_t)3; i1++){
if ((party == ALICE)) {
cin >> __tmp_in_y;
}
y[i0][i1] = Integer(bitlen, __tmp_in_y, ALICE);
}
}

Integer acc = Integer(bitlen,  (uint64_t)0, PUBLIC);
for (uint32_t i =  (int32_t)0; i <  (int32_t)2; i++){
for (uint32_t j =  (int32_t)0; j <  (int32_t)3; j++){
acc = acc.operator+(y[i][j].operator-(x[i][j]));
}
}
cout << ("Value of acc:") << endl;
cout << (acc.reveal<uint64_t>(PUBLIC)) << endl;


finalize_semi_honest();
delete io; 
 
return 0;
}

