/*
This is an autogenerated file, generated using the EzPC compiler.
*/

#include "emp-sh2pc/emp-sh2pc.h" 
using namespace emp;
using namespace std;
int bitlen = 32;
int party,port;
char *ip = "127.0.0.1"; 
template<typename T> 
vector<T> make_vector(size_t size) { 
return std::vector<T>(size); 
} 

template <typename T, typename... Args> 
auto make_vector(size_t first, Args... sizes) 
{ 
auto inner = make_vector<T>(sizes...); 
return vector<decltype(inner)>(first, inner); 
} 


int main(int argc, char** argv) {
parse_party_and_port(argv, &party, &port);
if(argc>3){
  ip=argv[3];
}
cout<<"Ip Address: "<<ip<<endl;
cout<<"Port: "<<port<<endl;
cout<<"Party: "<<(party==1? "CLIENT" : "SERVER")<<endl;
NetIO * io = new NetIO(party==ALICE ? nullptr : ip, port);
setup_semi_honest(io, party);


auto yy = make_vector<Float>( (int32_t)10);

Float y = Float(1., PUBLIC);
yy[ (int32_t)0] = y;

int32_t i =  (int32_t)1;
while ((i <  (int32_t)10)) {
y = y.operator/(Float(2., PUBLIC));
yy[i] = yy[(i -  (int32_t)1)].operator+(y);
i = (i +  (int32_t)1);
}

cout << ("Value of yy:") << endl;
for (uint32_t i0 =  (uint32_t)0; i0 <  (int32_t)10; i0++){
cout << (yy[i0].reveal<string>(PUBLIC)) << endl;
}


finalize_semi_honest();
delete io; 
 
return 0;
}

