name: Athos CI Testing

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  ABY:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 
      image: drunkenlegend/ezpcsetup:latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: Update Git
        run: |
            add-apt-repository ppa:git-core/ppa -y
            apt-get update
            apt-get install git -y 

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            submodules: 'true'

      - name: Setup and Test ABY
        env:
            HOME: /root
            OPAM_SWITCH_PREFIX: /root/.opam/4.10.0
            CAML_LD_LIBRARY_PATH: /root/.opam/4.10.0/lib/stublibs:/root/.opam/4.10.0/lib/ocaml/stublibs:/root/.opam/4.10.0/lib/ocaml
            OCAML_TOPLEVEL_PATH: /root/.opam/4.10.0/lib/toplevel
            MANPATH: :/root/.opam/4.10.0/man
            PATH: /root/.opam/4.10.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        run: |
          cd EzPC/EzPC/
          git clone --recursive https://github.com/encryptogroup/ABY.git
          cd ABY/
          mkdir build && cd build
          cmake -DCMAKE_INSTALL_PREFIX=./install -DABY_BUILD_EXE=On ..
          cmake --build . --target install --parallel
          cd ../..
          eval $(opam config env)
          make
          chmod +x runtests.sh
          make runtest
          cd ../..

  EMP:
    runs-on: ubuntu-latest
    container: 
      image: drunkenlegend/ezpcsetup:latest
    steps:

      - name: Update Git
        run: |
            add-apt-repository ppa:git-core/ppa -y
            apt-get update
            apt-get install git -y

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            submodules: 'true'
      
      - name: Setup and Test EMP
        env:
          HOME: /root
          OPAM_SWITCH_PREFIX: /root/.opam/4.10.0
          CAML_LD_LIBRARY_PATH: /root/.opam/4.10.0/lib/stublibs:/root/.opam/4.10.0/lib/ocaml/stublibs:/root/.opam/4.10.0/lib/ocaml
          OCAML_TOPLEVEL_PATH: /root/.opam/4.10.0/lib/toplevel
          MANPATH: :/root/.opam/4.10.0/man
          PATH: /root/.opam/4.10.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        run: |
            pwd
            cd EzPC/EzPC/
            make
            wget https://raw.githubusercontent.com/emp-toolkit/emp-readme/master/scripts/install.py
            python install.py --deps --tool --ot --sh2pc
            rm -rf install.py
            eval $(opam config env)
            chmod +x runemptests.sh
            ./runemptests.sh
            cd ../../
          
  ONNX-CPP:
    # The type of runner that the job will run on
      runs-on: ubuntu-latest
      container: 
        image: drunkenlegend/ezpcsetup:latest
    # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
    
      - name: Update Git
        run: |
            add-apt-repository ppa:git-core/ppa -y
            apt-get update
            apt-get install git -y 

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            submodules: 'true'

      - name: Test Athos ONNX-CPP
        if: always()
        env:
            HOME: /root
            OPAM_SWITCH_PREFIX: /root/.opam/4.10.0
            CAML_LD_LIBRARY_PATH: /root/.opam/4.10.0/lib/stublibs:/root/.opam/4.10.0/lib/ocaml/stublibs:/root/.opam/4.10.0/lib/ocaml
            OCAML_TOPLEVEL_PATH: /root/.opam/4.10.0/lib/toplevel
            MANPATH: :/root/.opam/4.10.0/man
            PATH: /root/.opam/4.10.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        run: |
            cd EzPC/EzPC/
            make
            cd ../..
            cd Athos/tests/onnx/unittests
            pytest --backend CPP
        shell: bash
        
  ONNX-SCI-OT:
    # The type of runner that the job will run on
      runs-on: ubuntu-latest
      container: 
        image: drunkenlegend/ezpcsetup:latest
    # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
    
      - name: Update Git
        run: |
            add-apt-repository ppa:git-core/ppa -y
            apt-get update
            apt-get install git -y 
            
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            submodules: 'true'
      - name: Setup SCI
        run: |
            cd SCI
            mkdir -p build
            cd build
            cmake -DCMAKE_INSTALL_PREFIX=./install ../
            cmake --build . --target install --parallel
            cd ../..

      - name: Test Athos ONNX-SCI-OT
        if: always()
        env:
            HOME: /root
            OPAM_SWITCH_PREFIX: /root/.opam/4.10.0
            CAML_LD_LIBRARY_PATH: /root/.opam/4.10.0/lib/stublibs:/root/.opam/4.10.0/lib/ocaml/stublibs:/root/.opam/4.10.0/lib/ocaml
            OCAML_TOPLEVEL_PATH: /root/.opam/4.10.0/lib/toplevel
            MANPATH: :/root/.opam/4.10.0/man
            PATH: /root/.opam/4.10.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        run: |
            cd EzPC/EzPC/
            make
            cd ../..
            cd Athos/tests/onnx/unittests
            pytest --backend 2PC_OT
        shell: bash
          
  FSS:
    # The type of runner that the job will run on
      runs-on: ubuntu-latest
      container: 
        image: kanav99/ezpc-llama:latest
        # options: "--entrypoint /bin/bash"
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: Update Git
          run: |
            add-apt-repository ppa:git-core/ppa -y
            apt-get update
            apt-get install git -y 
       
        - name: Checkout repository
          uses: actions/checkout@v3
          with:
            submodules: 'true'

        - name: Setup
          env:
            HOME: /root
            OPAM_SWITCH_PREFIX: /root/.opam/4.10.0
            CAML_LD_LIBRARY_PATH: /root/.opam/4.10.0/lib/stublibs:/root/.opam/4.10.0/lib/ocaml/stublibs:/root/.opam/4.10.0/lib/ocaml
            OCAML_TOPLEVEL_PATH: /root/.opam/4.10.0/lib/toplevel
            MANPATH: :/root/.opam/4.10.0/man
            PATH: /root/.opam/4.10.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
          run: |
            pwd
            cd EzPC/EzPC/
            make
            cd ../../
            sudo ln -s `pwd`/EzPC/EzPC/fssc /usr/local/bin/fssc
            cd FSS/
            mkdir build
            cd build
            pwd
            cmake -DCMAKE_INSTALL_PREFIX=./install -DCMAKE_BUILD_TYPE=Release ../
            make install
            cd ../../
          shell: bash
        - name: Test
          env:
            HOME: /root
          run: |
            cd FSS/tests
            ./runall.sh
  

  
