/*
This is an autogenerated file, generated using the EzPC compiler.
*/

#include "emp-sh2pc/emp-sh2pc.h" 
using namespace emp;
using namespace std;
int bitlen = 32;
int party,port;
char *ip = "127.0.0.1"; 
template<typename T> 
vector<T> make_vector(size_t size) { 
return std::vector<T>(size); 
} 

template <typename T, typename... Args> 
auto make_vector(size_t first, Args... sizes) 
{ 
auto inner = make_vector<T>(sizes...); 
return vector<decltype(inner)>(first, inner); 
} 


int main(int argc, char** argv) {
parse_party_and_port(argv, &party, &port);
if(argc>3){
  ip=argv[3];
}
cout<<"Ip Address: "<<ip<<endl;
cout<<"Port: "<<port<<endl;
cout<<"Party: "<<(party==1? "CLIENT" : "SERVER")<<endl;
NetIO * io = new NetIO(party==ALICE ? nullptr : ip, port);
setup_semi_honest(io, party);


Integer a = Integer(bitlen,  (uint32_t)5, PUBLIC);

Integer b = Integer(bitlen,  (uint32_t)10, PUBLIC);

Integer c;

Bit e;

uint32_t d;
c = a.operator+(b);
c = a.operator-(b);
c = a.operator*(b);
/* Temporary variable for sub-expression on source location: (40,7-40,9) */
Integer __tac_var1 = Integer(bitlen,  (uint32_t)4, PUBLIC);
c = b.operator/(__tac_var1);
d = ( (uint32_t)10 %  (uint32_t)4);
/* Temporary variable for sub-expression on source location: (42,5-42,6) */
Integer __tac_var2 = b;
/* Temporary variable for sub-expression on source location: (42,5-42,10) */
Integer __tac_var3 = __tac_var2.operator>>( (uint32_t)2);
c = __tac_var3;
/* Temporary variable for sub-expression on source location: (43,5-43,6) */
Integer __tac_var4 = __tac_var2;
/* Temporary variable for sub-expression on source location: (43,5-43,10) */
Integer __tac_var5 = __tac_var2.operator<<( (uint32_t)2);
c = __tac_var5;
/* Temporary variable for sub-expression on source location: (44,5-44,6) */
Integer __tac_var6 = a;
/* Temporary variable for sub-expression on source location: (44,7-44,8) */
Integer __tac_var7 = __tac_var2;
/* Temporary variable for sub-expression on source location: (44,5-44,8) */
Integer __tac_var8 = __tac_var6.operator^(__tac_var2);
c = __tac_var8;
/* Temporary variable for sub-expression on source location: (45,5-45,6) */
Integer __tac_var9 = __tac_var6;
/* Temporary variable for sub-expression on source location: (45,7-45,8) */
Integer __tac_var10 = __tac_var2;
/* Temporary variable for sub-expression on source location: (45,5-45,8) */
Integer __tac_var11 = __tac_var6.operator&(__tac_var2);
c = __tac_var11;
/* Temporary variable for sub-expression on source location: (46,5-46,6) */
Integer __tac_var12 = __tac_var6;
/* Temporary variable for sub-expression on source location: (46,7-46,8) */
Integer __tac_var13 = __tac_var2;
/* Temporary variable for sub-expression on source location: (46,5-46,8) */
Integer __tac_var14 = __tac_var6.operator|(__tac_var2);
c = __tac_var14;
/* Temporary variable for sub-expression on source location: (47,5-47,10) */
int32_t __tac_var15 = (pow( (int32_t)2,  (int32_t)10));
c = Integer(bitlen, __tac_var15, PUBLIC);
/* Temporary variable for sub-expression on source location: (48,5-48,6) */
Integer __tac_var16 = __tac_var2;
/* Temporary variable for sub-expression on source location: (48,5-48,11) */
Integer __tac_var17 = __tac_var2.operator>>( (uint32_t)2);
c = __tac_var17;
/* Temporary variable for sub-expression on source location: (49,5-49,16) */
bool __tac_var18 = (1 && 0);
e = Bit(__tac_var18, PUBLIC);
/* Temporary variable for sub-expression on source location: (50,5-50,17) */
bool __tac_var19 = (0 || 0);
e = Bit(__tac_var19, PUBLIC);
/* Temporary variable for sub-expression on source location: (51,5-51,15) */
bool __tac_var20 = (0 ^ 1);
e = Bit(__tac_var20, PUBLIC);
/* Temporary variable for sub-expression on source location: (52,5-52,6) */
Integer __tac_var21 = __tac_var6;
/* Temporary variable for sub-expression on source location: (52,7-52,8) */
Integer __tac_var22 = __tac_var2;
e = __tac_var6.operator>(__tac_var2);
/* Temporary variable for sub-expression on source location: (53,6-53,7) */
Integer __tac_var23 = __tac_var6;
/* Temporary variable for sub-expression on source location: (53,9-53,10) */
Integer __tac_var24 = __tac_var2;
e = __tac_var6.operator==(__tac_var2);
/* Temporary variable for sub-expression on source location: (54,5-54,6) */
Integer __tac_var25 = __tac_var6;
/* Temporary variable for sub-expression on source location: (54,8-54,9) */
Integer __tac_var26 = __tac_var2;
e = __tac_var6.operator>=(__tac_var2);
/* Temporary variable for sub-expression on source location: (55,5-55,6) */
Integer __tac_var27 = __tac_var6;
/* Temporary variable for sub-expression on source location: (55,8-55,9) */
Integer __tac_var28 = __tac_var2;
e = __tac_var6.operator<=(__tac_var2);
/* Temporary variable for sub-expression on source location: (56,5-56,6) */
Integer __tac_var29 = __tac_var6;
/* Temporary variable for sub-expression on source location: (56,7-56,8) */
Integer __tac_var30 = __tac_var2;
e = __tac_var6.operator<(__tac_var2);


finalize_semi_honest();
delete io; 
 
return 0;
}

