/*
This is an autogenerated file, generated using the EzPC compiler.
*/

#include "emp-sh2pc/emp-sh2pc.h" 
using namespace emp;
using namespace std;
int bitlen = 32;
int party,port;
char *ip = "127.0.0.1"; 
template<typename T> 
vector<T> make_vector(size_t size) { 
return std::vector<T>(size); 
} 

template <typename T, typename... Args> 
auto make_vector(size_t first, Args... sizes) 
{ 
auto inner = make_vector<T>(sizes...); 
return vector<decltype(inner)>(first, inner); 
} 


int main(int argc, char** argv) {
parse_party_and_port(argv, &party, &port);
if(argc>3){
  ip=argv[3];
}
cout<<"Ip Address: "<<ip<<endl;
cout<<"Port: "<<port<<endl;
cout<<"Party: "<<(party==1? "CLIENT" : "SERVER")<<endl;
NetIO * io = new NetIO(party==ALICE ? nullptr : ip, port);
setup_semi_honest(io, party);


Integer x1 = Integer(bitlen,  (uint32_t)1, PUBLIC);

uint32_t x2 =  (uint32_t)2;

Integer x3 = Integer(bitlen,  (int32_t)1, PUBLIC);

int32_t x4 =  (int32_t)2;

Integer x5 = Integer(bitlen,  (int32_t)2, PUBLIC);

Integer x6 = x5;

Bit x7 = Bit(0, PUBLIC);


finalize_semi_honest();
delete io; 
 
return 0;
}

