/*
This is an autogenerated file, generated using the EzPC compiler.
*/

#include "emp-sh2pc/emp-sh2pc.h" 
using namespace emp;
using namespace std;
int bitlen = 32;
int party,port;
char *ip = "127.0.0.1"; 
template<typename T> 
vector<T> make_vector(size_t size) { 
return std::vector<T>(size); 
} 

template <typename T, typename... Args> 
auto make_vector(size_t first, Args... sizes) 
{ 
auto inner = make_vector<T>(sizes...); 
return vector<decltype(inner)>(first, inner); 
} 


int main(int argc, char** argv) {
parse_party_and_port(argv, &party, &port);
if(argc>3){
  ip=argv[3];
}
cout<<"Ip Address: "<<ip<<endl;
cout<<"Port: "<<port<<endl;
cout<<"Party: "<<(party==1? "CLIENT" : "SERVER")<<endl;
NetIO * io = new NetIO(party==ALICE ? nullptr : ip, port);
setup_semi_honest(io, party);


Integer summ = Integer(bitlen,  (int32_t)0, PUBLIC);

int32_t N =  (int32_t)100;

auto arr = make_vector<Integer>( (int32_t)100);
for (uint32_t i =  (int32_t)0; i <  (int32_t)100; i++){
arr[i] = Integer(bitlen, i, PUBLIC);
}
for (uint32_t i =  (int32_t)0; i <  (int32_t)100; i++){
/* Temporary variable for sub-expression on source location: (42,16-42,22) */
Integer __tac_var1 = arr[i];
summ = summ.operator+(__tac_var1);
}
cout << ("Value of summ:") << endl;
cout << (summ.reveal<int32_t>(ALICE)) << endl;


finalize_semi_honest();
delete io; 
 
return 0;
}

